### ISSUE TITLE
crash with mod menu

### ISSUE THREAD

**Issue by SkillHeaven** [kyrptonaught/DiggusMaximus#12]
With the most recent version, and multiple versions of mod menu the game crashes when you try to open the config

**Comment by kyrptonaught** [comment]
Do you have a log?

**Comment by SkillHeaven** [comment]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 5/7/20 5:54 PM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: me.shedaniel.clothconfig2.api.ConfigBuilder.setTitle(Ljava/lang/String;)Lme/shedaniel/clothconfig2/api/ConfigBuilder;
	at net.kyrptonaught.diggusmaximus.config.modmenu.ModMenuIntegration.lambda$getConfigScreenFactory$22(ModMenuIntegration.java:34)
	at io.github.prospector.modmenu.api.ModMenuApi.lambda$getModConfigScreenFactory$1(ModMenuApi.java:76)
	at io.github.prospector.modmenu.ModMenu.getConfigScreen(ModMenu.java:44)
	at io.github.prospector.modmenu.gui.ModsScreen.lambda$init$1(ModsScreen.java:92)
	at net.minecraft.class_4185.method_25306(class_4185.java:20)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:150)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:86)
	at net.minecraft.class_437.method_25412(class_437.java:416)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:99)
	at net.minecraft.class_1041.method_15998(class_1041.java:301)
	at net.minecraft.class_310.method_1523(class_310.java:1027)
	at net.minecraft.class_310.method_1514(class_310.java:630)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.kyrptonaught.diggusmaximus.config.modmenu.ModMenuIntegration.lambda$getConfigScreenFactory$22(ModMenuIntegration.java:34)
	at io.github.prospector.modmenu.api.ModMenuApi.lambda$getModConfigScreenFactory$1(ModMenuApi.java:76)
	at io.github.prospector.modmenu.ModMenu.getConfigScreen(ModMenu.java:44)
	at io.github.prospector.modmenu.gui.ModsScreen.lambda$init$1(ModsScreen.java:92)
	at net.minecraft.class_4185.method_25306(class_4185.java:20)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:150)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:86)

-- Affected screen --
Details:
	Screen name: io.github.prospector.modmenu.gui.ModsScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:416)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:99)

-- Affected level --
Details:
	All players: 1 total; [class_746['SkillHeaven'/22558, l='ClientLevel', x=146.61, y=63.00, z=130.52]]
	Chunk stats: Client Chunk Cache: 1369, 1024
	Level dimension: minecraft:overworld
	Level seed: -2638243926404761443
	Level generator options: NBT[{}]
	Level spawn location: World: (176,71,-96), Chunk: (at 0,4,0 in 11,-6; contains blocks 176,0,-96 to 191,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 329109 game time, 581638 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:435)
	at net.minecraft.class_310.method_1587(class_310.java:1980)
	at net.minecraft.class_310.method_1514(class_310.java:648)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 20w18a
	Minecraft Version ID: 20w18a
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2661426624 bytes (2538 MB) / 3603431424 bytes (3436 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx5120m
	Fabric Mods: 
		amecsapi: Amecs API 1.0.1+20w17a
		appleskin: AppleSkin 1.0.9
		autoconfig1u: Auto Config v1 Updated 3.0.1-unstable
		biow0rks: biow0rk5 0.4.4-1.16
		blue_endless_jankson: jankson +
		cloth: Cloth Events 2.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.0
		cloth-config2: Cloth Config v2 4.0.7-unstable
		diggusmaximus: Diggus Maximus 1.2.9-1.16
		fabric: Fabric API 0.10.1+build.336-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c34
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.2+2fd224cae8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89e8
		fabric-command-api-v1: Fabric Command API (v1) 1.0.0+52d30836e8
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d30836e8
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b6e8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.5+88afe607e8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825de8
		fabric-dimensions-v1: fabric-dimensions-v1 0.4.1+686e6e57e8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b99794e8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+1a47cd78e8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.12+2fd224cae8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d634
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff2e8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9934
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6e8
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7be8
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd7834
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.1+bf7c167ae8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.0+bf7c167ae8
		fabric-particles-v1: fabric-particles-v1 0.1.2+12a8474ce8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.1+686e6e57e8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.12+12a8474ce8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.29+6c0e72dfe8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60e8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825de8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474ce8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+53410490e8
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+24a100d8e8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.14+2fd224cae8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.4+2fd224ca34
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba7e8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.3+686e6e57e8
		fabricloader: Fabric Loader 0.8.2+build.194
		gbfabrictools: GBfabrictools 1.2.1.20w17a
		jankson: Jankson 2.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.0.0-1.16
		libcd: LibCapableData 2.4.0+20w17a
		lightoverlay: Light Overlay 5.2.1-unstable
		mcf-reap: MaxVar reap for fabric 1.3.1-16s
		minecraft: Minecraft 1.16-alpha.20.18.a
		modmenu: Mod Menu 1.11.4+build.9
		moenchantments: Mo'Enchantments 1.11.0
		mousewheelie: Mouse Wheelie 1.4.7+mc20w17a
		mycommands: MyCommands Fabric 20w17a-06
		reborncore: Reborn Core 4.2.9+build.20
		ring_of_growth: Ring Of Growth 1.0.1
		roughlyenoughitems: Roughly Enough Items 4.3.1-unstable
		simpledrawers: Simple Drawers 1.7.1-20w18a
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.3.11+build.25
		tweed: Tweed API 2.2.12
		vanilla-hammers: Vanilla Hammers 1.7.0
		voxelmap: VoxelMap 1.9.17
		worldtime: WorldTime 20w17a-fabric0.6.2-1.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz

**Comment by kyrptonaught** [comment]
Ah 20w18a, I have not updated to that snapshot yet

**Comment by SkillHeaven** [comment]
it does it in 20w16a, and 20w17a as well. I can get a crash log of them. I just don't want to right now lol

**Comment by kyrptonaught** [comment]
It’s actually due to a change in cloth config that I haven’t updated to account for. Downgrading cloth config might fix the issue

**Comment by SkillHeaven** [comment]
Ahh alright. Thanks for the info

**Comment by giveashift** [comment]
Came here to report this as well but you already know. Here's the log from RC1 though anyways incase it'll help when you do decide to update.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/21/20 8:46 AM
Description: Rendering screen

java.lang.NoSuchMethodError: me.shedaniel.clothconfig2.api.ConfigBuilder.setTitle(Ljava/lang/String;)Lme/shedaniel/clothconfig2/api/ConfigBuilder;
	at net.kyrptonaught.diggusmaximus.config.modmenu.ModMenuIntegration.lambda$getConfigScreenFactory$22(ModMenuIntegration.java:34)
	at net.kyrptonaught.diggusmaximus.config.modmenu.ModMenuIntegration$$Lambda$5560/1554085806.apply(Unknown Source)
	at io.github.prospector.modmenu.api.ModMenuApi.lambda$getModConfigScreenFactory$1(ModMenuApi.java:57)
	at io.github.prospector.modmenu.api.ModMenuApi$$Lambda$2321/252620129.create(Unknown Source)
	at io.github.prospector.modmenu.ModMenu.hasConfigScreenFactory(ModMenu.java:40)
	at io.github.prospector.modmenu.gui.ModsScreen$1.method_25394(ModsScreen.java:108)
	at net.minecraft.class_437.method_25394(class_437.java:81)
	at io.github.prospector.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:233)
	at net.minecraft.class_757.method_3192(class_757.java:603)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.kyrptonaught.diggusmaximus.config.modmenu.ModMenuIntegration.lambda$getConfigScreenFactory$22(ModMenuIntegration.java:34)
	at net.kyrptonaught.diggusmaximus.config.modmenu.ModMenuIntegration$$Lambda$5560/1554085806.apply(Unknown Source)
	at io.github.prospector.modmenu.api.ModMenuApi.lambda$getModConfigScreenFactory$1(ModMenuApi.java:57)
	at io.github.prospector.modmenu.api.ModMenuApi$$Lambda$2321/252620129.create(Unknown Source)
	at io.github.prospector.modmenu.ModMenu.hasConfigScreenFactory(ModMenu.java:40)
	at io.github.prospector.modmenu.gui.ModsScreen$1.method_25394(ModsScreen.java:108)
	at net.minecraft.class_437.method_25394(class_437.java:81)
	at io.github.prospector.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:233)

-- Screen render details --
Details:
	Screen name: io.github.prospector.modmenu.gui.ModsScreen
	Mouse location: Scaled: (292, 163). Absolute: (878.000000, 491.000000)
	Screen size: Scaled: (640, 329). Absolute: (1920, 986). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Giveashift'/172, l='ClientLevel', x=-120.77, y=44.00, z=-137.15]]
	Chunk stats: Client Chunk Cache: 841, 552
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,71,-128), Chunk: (at 0,4,0 in -8,-8; contains blocks -128,0,-128 to -113,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 9025 game time, 9025 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16 Release Candidate 1
	Minecraft Version ID: 1.16-rc1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1223727088 bytes (1167 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		blue_endless_jankson: jankson +
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.2
		cloth-config2: Cloth Config v4 4.4.0
		diggusmaximus: Diggus Maximus 1.2.9-1.16
		durabilityviewer: Giselbaers Durability Viewer 1.16-rc1-fabric0.12.5-1.7.1
		easierchests: EasierChests 1.16-rc1-fabric0.12.5-1.4
		easiervillagertrading: EasierVillagerTrading 1.16-rc1-fabric0.12.5-1.5
		fabric: Fabric API 0.12.5+build.367-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea8667c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea897c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533987c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308367c
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f7c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8667c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d7c
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b30537c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.3+0d474ec47c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96367c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a97747c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c57c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea8667c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce997c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d67c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b7c
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd787c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.4+059ea8667c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad67c
		fabric-particles-v1: fabric-particles-v1 0.1.3+4a08d6b27c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c7c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb87c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.1+059ea8667c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a607c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d7c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c7c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104907c
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d77c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea86671
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e7c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.5+5a6e8f4c7c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb87c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e7c
		fabricloader: Fabric Loader 0.8.8+build.202
		gbfabrictools: GBfabrictools 1.2.1.1.16-rc1
		kyrptconfig: Kytpt Config 1.0.0-1.16
		lvmnt: SuperAxes 1.0.9
		malilib: MaLiLib 0.10.0-dev.21+beta.1
		minecraft: Minecraft 1.16-rc.9
		minihud: MiniHUD 0.19.0-dev.20200610.220909
		mixedslab: Mixed Slab 20w20b-fabric-1.0.0.0
		modmenu: Mod Menu 1.12.1+build.15
		okzoomer: Ok Zoomer 3.0.1-20w12a
		roughlyenoughitems: Roughly Enough Items 4.5.2
		verticalslabs: Vertical Slabs 1.3.0
		voxelmap: VoxelMap 1.10.0
	Launched Version: fabric-loader-0.8.8+build.202-1.16-rc1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/1.15.2-r1.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor
