### ISSUE TITLE
1.15.2 crashes on server

### ISSUE THREAD

**Issue by Suyashtnt** [kyrptonaught/DiggusMaximus#13]
I installed it, worked on my server for 1 day then stopped and crashed my server
log:
`[08:02:18] [main/INFO]: Loading for game Minecraft 1.15.2
[08:02:21] [main/WARN]: Mod `bettersleeping` (0.3.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[08:02:21] [main/INFO]: [FabricLoader] Loading 75 mods: craftpresence@1.6.5, fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-keybindings-v0@0.1.1+dfdb52d60c, couplings@1.3.1, fabricloader@0.8.4+build.198, artifice@0.6.0+1.15.2, bettersleeping@0.3.0, moenchantments@1.9.6, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.3.0+2ad156310c, fabric-object-builder-api-v1@1.1.0+3e5587510c, extrabows@v1.15.1 Fabric b2, conveyance@0.3.3+1.15.2, extrapieces@2.8.3, fermion-modkeys@1.5.148, fabric-api-base@0.1.2+b7f9825d0c, reborncore@4.2.9+build.115, diggusmaximus@1.2.9, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-textures-v0@1.0.4+821cdba70c, creativebuttonmover@0.1.2, ninjaphenix-container-lib@0.1.6, fabric-rendering-fluids-v1@0.1.6+12515ed90c, glassdoor@1.4.3, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, me_shedaniel_cloth_basic-math@0.3.0, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, immersive_portals@0.29, libblockattributes_items@0.6.3, fabric-loot-tables-v1@0.1.5+e08a73050c, biow0rks@0.4.0, fabric@0.10.8+build.310-1.15, carpet@1.3.23, fabric-particles-v1@0.1.2+ad2f81bd0c, libblockattributes_core@0.6.3, fabric-networking-v0@0.1.7+003643510c, techreborn@3.3.11+build.224, wrenchable@0.2.2+1.15.2, cloth@1.2.0, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, modmenu@1.10.1+build.30, cloth-basic-math@0.5.0, jankson@2.0.1+j1.2.0, fabric-command-api-v1@1.0.2+2aebb7ff0c, fabric-tool-attribute-api-v1@1.1.0+3e5587510c, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-biomes-v1@0.1.5+3b05f68e0c, roughlyenoughitems@3.6.14, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.3.0+fac69e320c, kyrptconfig@1.0.0, fabric-rendering-v0@1.1.0+534104900c, infinityfix@1.1.0, fabric-rendering-v1@1.0.0+2a034f0a0c, cloth-config2@2.13.4, autoconfig1u@2.0.1, fabric-resource-loader-v0@0.1.10+06c939b30c, chainmail@0.1.0, expandedstorage@5.0.1, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, blue_endless_jankson@+, tinyconfig@1.1.2, appleskin@1.0.8, fabric-commands-v0@0.2.0+2e0c4ff50c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-mining-levels-v0@0.1.2+ec951ea40c, fabric-climbable-api-v1@1.0.0+6ffe71e20c, fabric-events-lifecycle-v0@0.1.2+003643510c, fabric-item-groups-v0@0.1.6+045efb460c, fabric-models-v0@0.1.0+dfdb52d60c, team_reborn_energy@0.1.0, fabric-object-builders-v0@0.5.1+3e5587510c, org_jetbrains_annotations@18.0.0
[08:02:21] [main/WARN]: Mod `extrabows` (v1.15.1 Fabric b2) does not respect SemVer - comparison support is limited.
[08:02:21] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[08:02:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/aternos/server/fabric.jar Service=Knot/Fabric Env=SERVER
[08:02:23] [main/WARN]: Reference map 'wrenchable-refmap.json' for wrenchable.mixins.json could not be read. If this is a development environment you can ignore this message
[08:02:24] [main/FATAL]: Mixin prepare failed preparing MixinBlockBreak in diggusmaximus.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class net.kyrptonaught.diggusmaximus.mixin.MixinBlockBreak in environment type SERVER
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class net.kyrptonaught.diggusmaximus.mixin.MixinBlockBreak in environment type SERVER
at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855) ~[fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515) [fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_222]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190) [fabric.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class net.kyrptonaught.diggusmaximus.mixin.MixinBlockBreak in environment type SERVER
at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:76) ~[fabric.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[fabric.jar:?]
at net.fabricmc.loader.launch.knot.Knot.getClassByteArray(Knot.java:208) ~[fabric.jar:?]
at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:47) ~[fabric.jar:?]
at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:63) ~[fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1295) ~[fabric.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[fabric.jar:?]
... 22 more
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [diggusmaximus.mixins.json:MixinBlockBreak] from phase [DEFAULT] in config [diggusmaximus.mixins.json] FAILED during PREPARE
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:591)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:518)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class net.kyrptonaught.diggusmaximus.mixin.MixinBlockBreak in environment type SERVER
at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855)
at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)
... 19 more
Caused by: java.lang.RuntimeException: Cannot load class net.kyrptonaught.diggusmaximus.mixin.MixinBlockBreak in environment type SERVER
at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:76)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185)`

**Comment by kyrptonaught** [comment]
Wow I am amazed this hasn’t been caught until now. I’ll work on a fix

**Comment by kyrptonaught** [comment]
This should be fixed in 1.2.10

**Comment by snostormjp** [comment]
Not exactly related to 1.15.2 , but I tried the latest on 20w21a snapshot and had a similar error where it crashed the server , but not single player.  I went into commits and pulled the 1.3 jar file from 13aa1d7e6f362c6d1acbc29d3dcbcfe6e994b770  and every thing worked fine on server and client.

**Comment by Suyashtnt** [comment]
Ok I recently got to play again and it works!
