### ISSUE TITLE
[19w46b] illegal access error

### ISSUE THREAD

**Issue by Yoghurt4C** [kyrptonaught/DiggusMaximus#4]
```java
Description: Unexpected error

java.lang.IllegalAccessError: Class net/kyrptonaught/diggusmaximus/DiggusMaximusMod illegally accessing "private" member of class net/minecraft/class_310
	at net.kyrptonaught.diggusmaximus.DiggusMaximusMod.isKeybindPressed(DiggusMaximusMod.java:33)
	at net.minecraft.class_2248.handler$zed000$DIGGUS$BLOCKBREAK(class_2248.java:1641)
	at net.minecraft.class_2248.method_9576(class_2248.java)
	at net.minecraft.class_636.method_2899(class_636.java:113)
	at net.minecraft.class_636.method_2921(class_636.java:74)
	at net.minecraft.class_636.method_2910(class_636.java:143)
	at net.minecraft.class_310.method_1536(class_310.java:1243)
	at net.minecraft.class_310.method_1508(class_310.java:1531)
	at net.minecraft.class_310.method_1574(class_310.java:1381)
	at net.minecraft.class_310.method_1523(class_310.java:907)
	at net.minecraft.class_310.method_1514(class_310.java:569)
	at net.minecraft.client.main.Main.main(Main.java:202)
```

**Comment by kyrptonaught** [comment]
Looks like it’s time I actually update to the snapshots, I’ll take a look at this tomorrow. Thanks for the report

**Comment by kyrptonaught** [comment]
Diggus is now updated for the most recent snapshots, tested on 1.15pre1 and 19w45b. 
https://www.curseforge.com/minecraft/mc-mods/diggus-maximus/files/2831553
