### ISSUE TITLE
Can't start server on 1.19. Tried redownloading and deleting config files.

### ISSUE THREAD

**Issue by gabelallen03** [kyrptonaught/DiggusMaximus#51]
[12:07:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Gabe/Desktop/Server/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[12:07:30] [main/INFO]: Compatibility level set to JAVA_17
[12:07:34] [main/INFO]: Building unoptimized datafixer
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Config not found! Creating one.
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Failed to load config! Overwriting with default config.
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Config not found! Creating one.
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Failed to load config! Overwriting with default config.
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Config not found! Creating one.
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Failed to load config! Overwriting with default config.
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Config not found! Creating one.
[12:07:36] [main/INFO]: [STDOUT]: diggusmaximus Failed to load config! Overwriting with default config.
[12:07:36] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'diggusmaximus'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.6.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3675$class_306
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Class.java:3329) ~[?:?]
        at java.lang.Class.privateGetPublicFields(Class.java:3356) ~[?:?]
        at java.lang.Class.privateGetPublicFields(Class.java:3366) ~[?:?]
        at java.lang.Class.getFields(Class.java:1960) ~[?:?]
        at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:408) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
        at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:424) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
        at blue.endless.jankson.Jankson.toJson(Jankson.java:312) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigStorage.save(ConfigStorage.java:26) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigManager.lambda$save$0(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigManager.save(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigManager.load(ConfigManager.java:38) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at net.kyrptonaught.diggusmaximus.DiggusMaximusMod.onInitialize(DiggusMaximusMod.java:23) ~[diggusmaximus-1.5.5-1.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3675$class_306
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Class.java:3329) ~[?:?]
        at java.lang.Class.privateGetPublicFields(Class.java:3356) ~[?:?]
        at java.lang.Class.privateGetPublicFields(Class.java:3366) ~[?:?]
        at java.lang.Class.getFields(Class.java:1960) ~[?:?]
        at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:408) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
        at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:424) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
        at blue.endless.jankson.Jankson.toJson(Jankson.java:312) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigStorage.save(ConfigStorage.java:26) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigManager.lambda$save$0(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigManager.save(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at net.kyrptonaught.kyrptconfig.config.ConfigManager.load(ConfigManager.java:38) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
        at net.kyrptonaught.diggusmaximus.DiggusMaximusMod.onInitialize(DiggusMaximusMod.java:23) ~[diggusmaximus-1.5.5-1.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
        ... 7 more

C:\Users\Gabe\Desktop\Server>pause
Press any key to continue . . .

**Comment by kyrptonaught** [comment]
Can you post the full log?

**Comment by molehzy** [comment]
That's full log
<details><summary>latest.log</summary>

``` 
[07:59:02] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.6
[07:59:02] [main/INFO]: Loading 42 mods:
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- diggusmaximus 1.5.5-1.19
	- fabric 0.55.2+1.19
	- fabric-api-base 0.4.8+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.5+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.11+e62f51a3a9 via fabric
	- fabric-command-api-v1 1.2.4+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.0+cda9839ba9 via fabric
	- fabric-commands-v0 0.2.21+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.26+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.0.15+9ff28f40a9 via fabric
	- fabric-convention-tags-v1 1.0.7+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.2+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.0.0+2a5b9210a9 via fabric
	- fabric-dimensions-v1 2.1.26+72da3b3da9 via fabric
	- fabric-entity-events-v1 1.4.15+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.25+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.23+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.18+18990361a9 via fabric
	- fabric-item-api-v1 1.5.3+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.22+9ff28f40a9 via fabric
	- fabric-lifecycle-events-v1 2.0.8+21a5acaaa9 via fabric
	- fabric-loot-api-v2 1.0.0+9e7660c6a9 via fabric
	- fabric-loot-tables-v1 1.1.0+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.0+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.6+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.26+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.13+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.4+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.7+9ff28f40a9 via fabric
	- fabric-registry-sync-v0 0.9.15+92cf9a3ea9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.11+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.4+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.8+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.2+9e7660c6a9 via fabric
	- fabric-screen-handler-api-v1 1.2.5+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.7+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+9e7660c6a9 via fabric
	- fabricloader 0.14.6
	- java 17
	- kyrptconfig 1.4.5-1.19 via diggusmaximus
	- minecraft 1.19
[07:59:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/F:/MCServer/1.19-Fabric/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[07:59:02] [main/INFO]: Compatibility level set to JAVA_17
[07:59:08] [main/INFO]: Building unoptimized datafixer
[07:59:10] [main/INFO]: [STDOUT]: diggusmaximus Failed to load config! Overwriting with default config.
[07:59:10] [main/INFO]: [STDOUT]: diggusmaximus Config not found! Creating one.
[07:59:10] [main/INFO]: [STDOUT]: diggusmaximus Failed to load config! Overwriting with default config.
[07:59:10] [main/INFO]: [STDOUT]: diggusmaximus Config not found! Creating one.
[07:59:10] [main/INFO]: [STDOUT]: diggusmaximus Failed to load config! Overwriting with default config.
[07:59:10] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'diggusmaximus'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.6.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3675$class_306
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.privateGetPublicFields(Class.java:3324) ~[?:?]
	at java.lang.Class.privateGetPublicFields(Class.java:3334) ~[?:?]
	at java.lang.Class.getFields(Class.java:1928) ~[?:?]
	at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:408) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
	at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:424) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
	at blue.endless.jankson.Jankson.toJson(Jankson.java:312) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigStorage.save(ConfigStorage.java:26) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigManager.lambda$save$0(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigManager.save(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigManager.load(ConfigManager.java:38) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at net.kyrptonaught.diggusmaximus.DiggusMaximusMod.onInitialize(DiggusMaximusMod.java:23) ~[diggusmaximus-1.5.5-1.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3675$class_306
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.privateGetPublicFields(Class.java:3324) ~[?:?]
	at java.lang.Class.privateGetPublicFields(Class.java:3334) ~[?:?]
	at java.lang.Class.getFields(Class.java:1928) ~[?:?]
	at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:408) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
	at blue.endless.jankson.impl.MarshallerImpl.serialize(MarshallerImpl.java:424) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
	at blue.endless.jankson.Jankson.toJson(Jankson.java:312) ~[blue_endless_jankson-1.2.1-4353a3994da55b73.jar:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigStorage.save(ConfigStorage.java:26) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigManager.lambda$save$0(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigManager.save(ConfigManager.java:33) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at net.kyrptonaught.kyrptconfig.config.ConfigManager.load(ConfigManager.java:38) ~[kyrptconfig-1.4.5-1.19-e3f634bfe1c8d803.jar:?]
	at net.kyrptonaught.diggusmaximus.DiggusMaximusMod.onInitialize(DiggusMaximusMod.java:23) ~[diggusmaximus-1.5.5-1.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
	... 7 more
``` 
</details>

**Comment by kyrptonaught** [comment]
This should be fixed in 1.5.6
