### ISSUE TITLE
Incompatible mod set!

### ISSUE THREAD

**Issue by 12345-mcpython** [kyrptonaught/DiggusMaximus#58]
DiggusMaximus: 1.5.8-1.19
Minecraft: 1.19
Fabric Loader: 0.14.7

[20:11:31] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.7
[20:11:32] [main/WARN]: Mod resolution failed
[20:11:32] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE diggusmaximus 1.5.8-1.19 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE diggusmaximus 1.5.8-1.19]
[20:11:32] [main/INFO]: Reason: [HARD_DEP diggusmaximus 1.5.8-1.19 {depends fabric @ [*]}, HARD_DEP kyrptconfig 1.4.14-1.19 {depends fabric @ [*]}]
[20:11:32] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[20:11:32] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Diggus Maximus' (diggusmaximus) 1.5.8-1.19 requires any version of fabric, which is missing!
	 - Mod 'Kyrpt Config' (kyrptconfig) 1.4.14-1.19 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]

**Comment by kyrptonaught** [comment]
Did you install Fabric Api? This is a separate mod available for download on curseforge.

**Comment by 12345-mcpython** [comment]
OK.I fixed it.
